name: PR Source Branch Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        if: github.event.pull_request.base.ref == 'main'
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "develop" ]; then
            echo "❌ Error: Pull requests to main must come from develop branch."
            exit 1
          fi
